"""empty message

Revision ID: 7bcacc44897d
Revises: 6aab94dd397a
Create Date: 2023-12-22 00:01:44.512367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bcacc44897d'
down_revision = '6aab94dd397a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.alter_column('password_hash2',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('password_hash2',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)

    op.drop_table('file')
    # ### end Alembic commands ###
